import React from 'react'

export default function MetadataDetails() {
  return (
    <div>
      sion potential is low at a recompression cycle respectively in a new
      saving and results in darker color on the ELA view. By contrast, irregular
      patterns containing fine contours and complex color and brightness
      gradients will show just few redundancies, which can not be reduced so
      well. Repeated saving of a JPG image removes high-frequency parts of an
      image and reduces the differences between strongly contrasting edges,
      textures and surfaces. A JPG image that is stored in the lowest quality
      level is displayed accordingly much darker than at higher quality levels.
      image Click to enlarge this image A JPEG file that creates a custom
      Huffman table based on statistical analysis of the respective image
      content, is called Progressive JPEG. Images generated by digital cameras,
      however, are not optimized in this way. Original shots from digital
      cameras should always have a high degree of change after a new save and
      thus
    </div>
  );
}
