name: Deploy Frontend

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci 

      - name: Build Frontend
        run: npm run build
        env:
          VITE_REACT_APP_API_URL: ${{ secrets.VITE_REACT_APP_API_URL }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }} -t ${{ secrets.DOCKERHUB_USERNAME }}/ispy-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ispy-frontend:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ispy-frontend:latest
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container -p 8080:80 \
              --restart always ${{ secrets.DOCKERHUB_USERNAME }}/ispy-frontend:latest
            sudo systemctl restart nginx